# Numpy

# Table of Contents

1. [Intro to numpy arrays](#1)
2. [Creating numpy array](#2)
3. [Loading text files](#3)
4. [Array shape and structure](#4)
5. [Indexing and slicing arrays](#5)
6. [Computations with umpy arrays](#6)
7. [Application of numpy in image analysis](#Application-of-numpy-for-image-analysis)

## Intro to numpy arrays 

In [1]:
import numpy as np
np.__version__

'2.3.3'

In [2]:
# why numpy ? 
# use lists for array addtion 
a = [1, 2, 3, 4, 5]
b = [11, 12, 13, 14, 15]
a+b

[1, 2, 3, 4, 5, 11, 12, 13, 14, 15]

In [6]:
sumab = []
for i in range(len(a)):
    sumab.append(a[i]+b[i])
#    sumab.append(sum([a[i],b[i]]))
    
sumab

[12, 14, 16, 18, 20]

In [3]:
sumab = [a[i]+b[i] for i in range(len(a))]
sumab

[12, 14, 16, 18, 20]

In [5]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([11, 12, 13, 14, 15])
print(a+b)

[12 14 16 18 20]


### Data types -
See the full list [here](https://numpy.org/doc/stable/user/basics.types.html#data-types)

`int8, uint8` - Signed and unsigned 8-bit (1 byte) integer types

`int16, uint16` - Signed and unsigned 16-bit integer types

`int32, uint32` - Signed and unsigned 32-bit integer types

`int64, uint64` - Signed and unsigned 64-bit integer types

`float16` - Half-precision floating point

`float32` - Standard single-precision floating point; compatible with C float

`float64` - Standard double-precision floating point

`float128` - Extended-precision floating point

`complex64, complex128, complex256` - Complex numbers represented by two 32, 64, or 128 floats, respectively

`bool` - Boolean type storing True and False values

`string` - Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use 'S10'



In [87]:
a_str = np.array(['3.2', '4.1','6.7'], dtype=np.string_) 
print(a_str.dtype)
print(a_str)
b = a_str.astype(np.float16)
print(b.dtype)
print(b)

|S3
[b'3.2' b'4.1' b'6.7']
float16
[3.2 4.1 6.7]


### Similarity between NumPy Array and list

`list`:  `[,]`
- Dynamically typed
- Ordered
- Mutable **values**
- Mutable **length**

`numpy.ndarray`:  `array([,])`
- Statically typed
- Ordered
- Mutable **values**
- Immutable **length**

### Differences between NumPy Array and list

 | Feature                | **Python List**                                           | **NumPy Array**                                                        |
| ---------------------- | --------------------------------------------------------- | ---------------------------------------------------------------------- |
| **Data types**         | Can hold mixed types (`[1, "a", 3.0]`)                    | All elements must be the same type (`[1.0, 2.0, 3.0]`)                 |
| **Storage**            | Each element is a Python object (slower, more memory)     | Stored in contiguous memory (efficient, compact)                       |
| **Math operations**    | Not supported element-wise: `[1,2,3] * 2 → [1,2,3,1,2,3]` | Element-wise operations: `np.array([1,2,3]) * 2 → [2,4,6]`             |
| **Performance**        | Slower for numerical computations                         | Much faster (uses C under the hood)                                    |
| **Dimensions**         | One-dimensional (nested lists for 2D, but clumsy)         | Supports true multi-dimensional arrays (1D, 2D, nD)                    |
| **Functions**          | Basic built-in functions (`sum(list)`, `len(list)`)       | Rich library: linear algebra, FFT, statistics, reshaping, broadcasting |
| **Indexing & slicing** | Simple indexing & slicing only                            | Advanced indexing: slices, masks, boolean conditions, broadcasting     |
| **Best use case**      | General purpose, mixed data, small collections            | Large numerical data, scientific/matrix computations                   |


## Creating numpy arrays 
https://wesmckinney.com/book/numpy-basics.html

In [6]:
# create one dimensional array
a = np.array([1,2,3,5])
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int64')

In [8]:
a = np.array([1.3, 2.4, 4.5])
a.dtype

dtype('float64')

In [9]:
a.ndim

1

In [10]:
a = np.asarray([3,4,6])
print(type(a))

<class 'numpy.ndarray'>


In [12]:
a.dtype

dtype('int64')

In [11]:
# shape returns a tuple listing the length of the arrays
a.shape

(3,)

In [13]:
# numpy is for the same data type only 
a[0] = 10.4
a

array([10,  4,  6])

In [14]:
#create a two dimensional array
a = np.array([[1,2,4,5,6,7,8],[5,6,7,8, 12, 9, 21]])
a

array([[ 1,  2,  4,  5,  6,  7,  8],
       [ 5,  6,  7,  8, 12,  9, 21]])

In [96]:
a.dtype

dtype('int32')

In [15]:

a.shape

(2, 7)

In [98]:
a.ndim

2

In [16]:
a[1,0:3]

array([5, 6, 7])

In [100]:
# create a 3D array with 2-D arrays
a = np.array([ [ [1,2,3], [4,5,6], [7,8,9]], [[10,11,12],[13,14,15], [16,17,18]] ])
a.shape

(2, 3, 3)

In [17]:
a = np.array([ [[1,2,3], [4,5,6]], [[10,11,12],[13,14,15]] ])
a.shape

(2, 2, 3)

In [8]:
a = np.array([ [[1,2,3,3],[4,5,6,6]], [[10,11,12,12],[13,14,15,15]],[[100,110,120,120],[130,140,150,150]] ])
a.shape

(3, 2, 4)

In [18]:
a = np.array([1, 2, 3.,4])
a.dtype

dtype('float64')

In [19]:
# itemsize() function returns the length of one array element in bytes.
a.itemsize

8

In [20]:
# numpy.ndarray.nbytes() function returns the total bytes consumed by the elements of the array.
# = num of elem*itemsize
a.nbytes

32

In [21]:
a = np.array([1, 2, 3.,255, 256], dtype ='uint8')
print(a)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)


OverflowError: Python integer 256 out of bounds for uint8

In [22]:
a = np.array([1, 2, 3.,257], dtype ='uint32')
print(a)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)


[  1   2   3 257]
uint32
4
16


In [11]:
a = np.array([1, 2, 3.,257], dtype ='float64')
print(a)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

[  1.   2.   3. 257.]
float64
32
8


## More on creating arrays
In addition to np.array, there are additional ways to [create special arrays](https://numpy.org/doc/stable/reference/routines.array-creation.html)
1. arange()
2. linespace()
3. array()
4. zeros()
5. ones()
6. full(n,filled value)

### arange()
Generate an array of values in the range [start, stop).
arange([start,] stop [, step], dtype = None). 
Similar to python range() function. Default dtype 
is derived from the start, stop and step values 

In [108]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(0,5,2)

array([0, 2, 4])

In [110]:
np.arange(0, 6, 2)

array([0, 2, 4])

In [16]:
# When using a non-integer step, such as 0.1, the results will often not be consistent.
# It is better to use numpy.linspace for these cases.

np.arange(1.0, 5.0, 1.0)

array([1., 2., 3., 4.])

In [17]:
np.arange(1.5, 2.1, 0.3)

array([1.5, 1.8, 2.1])

### linespace()
Generate N evenly spaced elements between (and including) start and stop values 

In [113]:
np.linspace(0, 2, 11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [114]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

### array()

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### zeros()

In [115]:
np.zeros((2,3), dtype='float64')

array([[0., 0., 0.],
       [0., 0., 0.]])

### ones()

In [24]:
np.ones( (4,5), dtype='uint8')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [21]:
a = np.zeros(5, dtype=int)
print(a)
#np.empty() - Return a new array of given shape and type, without initializing entries.
#empty , unlike numpy. zeros , does not set the array values to zero and, 
b = np.empty(5, dtype=int)
print(b)

[0 0 0 0 0]
[89351328      509        0        0        1]
[89351328      509        0        0        1]


In [24]:
a = np.ones(5)
print(a)

#numpy.ones_like() - Return an array of ones with the same shape and type as a given array.
a = np.ones_like(3)
print(a)

x = np.arange(6)
x = x.reshape((2, 3))
x
np.ones_like(x)


[1. 1. 1. 1. 1.]
1


array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
a = np.full(5,4)
print(a)

[4 4 4 4 4]


## Loading Text Files <a id=3></a>

In [25]:
np.loadtxt?

Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding=None,
    max_rows=None,
    *,
    quotechar=None,
    like=None,
)
Docstring:
Load data from a text file.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
    that generators must return bytes or strings. The strings
    in a list or produced by a generator are treated as lines.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or se

In [26]:
np.loadtxt('data/wind_simple.data')

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]], shape=(6574, 15))

In [74]:
print(data.dtype)
print(data.ndim)


float64
2


In [27]:
# predefined dtype
wind_dtype = [
    ('year', int),
    ('month', int),
    ('day', int),
    ('wind', float, (12,)),
]
data = np.loadtxt('data/wind_simple.data', dtype=wind_dtype)
data

array([(61,  1,  1, [15.04, 14.96, 13.17,  9.29, 13.96,  9.87, 13.67, 10.25, 10.83, 12.58, 18.5 , 15.04]),
       (61,  1,  2, [14.71, 16.88, 10.83,  6.5 , 12.62,  7.67, 11.5 , 10.04,  9.79,  9.67, 17.54, 13.83]),
       (61,  1,  3, [18.5 , 16.88, 12.33, 10.13, 11.17,  6.17, 11.25,  8.04,  8.5 ,  7.67, 12.75, 12.71]),
       ...,
       (78, 12, 29, [14.  , 10.29, 14.42,  8.71,  9.71, 10.54, 19.17, 12.46, 14.5 , 16.42, 18.88, 29.58]),
       (78, 12, 30, [18.5 , 14.04, 21.29,  9.13, 12.75,  9.71, 18.08, 12.87, 12.46, 12.12, 14.67, 28.79]),
       (78, 12, 31, [20.33, 17.41, 27.29,  9.59, 12.08, 10.13, 19.25, 11.63, 11.58, 11.38, 12.08, 22.08])],
      shape=(6574,), dtype=[('year', '<i8'), ('month', '<i8'), ('day', '<i8'), ('wind', '<f8', (12,))])

In [28]:
data['wind']

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]], shape=(6574, 12))

In [29]:
data['wind'].shape

(6574, 12)

In [30]:
print(data['year'].shape)
data['year']

(6574,)


array([61, 61, 61, ..., 78, 78, 78], shape=(6574,))

In [66]:
# Read only certain columns
data = np.loadtxt('data/wind_simple.data', usecols = (3,5)) # 4th and 6th columns
data

array([[15.04, 13.17],
       [14.71, 10.83],
       [18.5 , 12.33],
       ...,
       [14.  , 14.42],
       [18.5 , 21.29],
       [20.33, 27.29]], shape=(6574, 2))

### Loadd data using genfromtxt

Open `wind.data` and take a look.  It has a blank row, a header row, and missing values, shown by `NaN`

`np.genfromtxt` has more flexibility (but can be a little slower sometimes).  Explore `np.genfromtxt`'s `skip_header`, `names`, and `missing_values` keyword arguments.

- Use `np.genfromtxt` to load the more-complicated data in `wind.data`.
- Create `wind` that has just the wind speed measurements.

In [32]:
np.genfromtxt?

Signature:
np.genfromtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    skip_header=0,
    skip_footer=0,
    converters=None,
    missing_values=None,
    filling_values=None,
    usecols=None,
    names=None,
    excludelist=None,
    deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~",
    replace_space='_',
    autostrip=False,
    case_sensitive=True,
    defaultfmt='f%i',
    unpack=None,
    usemask=False,
    loose=True,
    invalid_raise=True,
    max_rows=None,
    encoding=None,
    *,
    ndmin=0,
    like=None,
)
Docstring:
Load data from a text file, with missing values handled as specified.

Each line past the first `skip_header` lines is split at the `delimiter`
character, and characters following the `comments` character are discarded.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is ``.gz`` or ``.bz2``, the file is first decompres

In [82]:
data = np.genfromtxt('data/wind.data', skip_header = 2, dtype = wind_dtype)
data

array([(61,  1,  1, [15.04, 14.96, 13.17,  9.29,   nan,  9.87, 13.67, 10.25, 10.83, 12.58, 18.5 , 15.04]),
       (61,  1,  2, [14.71,   nan, 10.83,  6.5 , 12.62,  7.67, 11.5 , 10.04,  9.79,  9.67, 17.54, 13.83]),
       (61,  1,  3, [18.5 , 16.88, 12.33, 10.13, 11.17,  6.17, 11.25,   nan,  8.5 ,  7.67, 12.75, 12.71]),
       ...,
       (78, 12, 29, [14.  , 10.29, 14.42,  8.71,  9.71, 10.54, 19.17, 12.46, 14.5 , 16.42, 18.88, 29.58]),
       (78, 12, 30, [18.5 , 14.04, 21.29,  9.13, 12.75,  9.71, 18.08, 12.87, 12.46, 12.12, 14.67, 28.79]),
       (78, 12, 31, [20.33, 17.41, 27.29,  9.59, 12.08, 10.13, 19.25, 11.63, 11.58, 11.38, 12.08, 22.08])],
      shape=(6574,), dtype=[('year', '<i8'), ('month', '<i8'), ('day', '<i8'), ('wind', '<f8', (12,))])

In [33]:
# use names to pull field names from the header rows.
# Note that it overwrites the field names in the structured dtype.
data = np.genfromtxt('data/wind.data', skip_header=1, names=True, dtype = wind_dtype)
data

array([(61,  1,  1, [15.04, 14.96, 13.17,  9.29,   nan,  9.87, 13.67, 10.25, 10.83, 12.58, 18.5 , 15.04]),
       (61,  1,  2, [14.71,   nan, 10.83,  6.5 , 12.62,  7.67, 11.5 , 10.04,  9.79,  9.67, 17.54, 13.83]),
       (61,  1,  3, [18.5 , 16.88, 12.33, 10.13, 11.17,  6.17, 11.25,   nan,  8.5 ,  7.67, 12.75, 12.71]),
       ...,
       (78, 12, 29, [14.  , 10.29, 14.42,  8.71,  9.71, 10.54, 19.17, 12.46, 14.5 , 16.42, 18.88, 29.58]),
       (78, 12, 30, [18.5 , 14.04, 21.29,  9.13, 12.75,  9.71, 18.08, 12.87, 12.46, 12.12, 14.67, 28.79]),
       (78, 12, 31, [20.33, 17.41, 27.29,  9.59, 12.08, 10.13, 19.25, 11.63, 11.58, 11.38, 12.08, 22.08])],
      shape=(6574,), dtype=[('Yr', '<i8'), ('Mo', '<i8'), ('Dy', '<i8'), ('RPT', '<f8', (12,))])

In [88]:
data.dtype.names

('Yr', 'Mo', 'Dy', 'RPT')

In [89]:
data['RPT']

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71,   nan, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]], shape=(6574, 12))

### Missing Data in NumPy

NumPy uses `np.nan` - "**n**ot **a** **n**umber" to represent missing or invalid data.

In [35]:
np.mean(data['RPT'])

np.float64(nan)

In [93]:
np.nanmean(data['RPT'])

np.float64(10.227883764282181)

## Array shape and structure

### Dimensions and axis

In [37]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [32]:
a.shape

(24,)

### Shape Definition and Manipulation

In [33]:
a.shape = (4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
a.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Convention on Display of Dimensions

![title](img/NumPy_Axes.png)

### Array Data Structure

![Array Data Structure](img/NumPy_Data_Structure.png)

In [42]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
a.shape = (2,12)

In [46]:
a.strides

(96, 8)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

## Slicing and indexing arrays 

Slicing in python means taking elements from one given index to another given index, like this: [start:end:step].
The lower-bound is inclusive, the upper-bound is exclusive. 

No upperbound if start = 0, no lower bound if end = length of dimension+1. 

If step == 1, we pass slice like this: [start:end] 

Numpy array slicing works like standard python slicing. 


In [104]:
a = np.array([1,2,3,4,5,6])
a[1:3]

array([2, 3])

In [105]:
a[:3:2]

array([1, 3])

In [106]:

a = np.array([[1,2,4,5,6,7,8],[5,6,7,8, 12, 9, 21]])
a

array([[ 1,  2,  4,  5,  6,  7,  8],
       [ 5,  6,  7,  8, 12,  9, 21]])

In [107]:
a[-1,1:3]

array([6, 7])

In [108]:
a[1::2,:3:2]

array([[5, 7]])

In [109]:
print(a)
a[0]

[[ 1  2  4  5  6  7  8]
 [ 5  6  7  8 12  9 21]]


array([1, 2, 4, 5, 6, 7, 8])

In [113]:
# create an array using arange and reshape
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [114]:
# print column 2 and 4, and last row
a[-1,1:4:2]

array([21, 23])

In [128]:
a[:,1:4:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [129]:
# slicing
a[:,1]

array([ 1,  6, 11, 16, 21])

In [130]:
a[:, -2]

array([ 3,  8, 13, 18, 23])

In [131]:
a[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

### Fancy Indexing - Indexing by positions 
Array indexing is the same as accessing an array element.
You can access an array element by referring to its index number.
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1.

In [132]:
a = np.arange(0, 80, 10)
print(a)

[ 0 10 20 30 40 50 60 70]


In [133]:
# get items
indices = [1, 2, -3]
y = a[indices]
y = a[[1,2,-3]]
y

array([10, 20, 50])

In [134]:
#set item values
a[indices] = 100
a

array([  0, 100, 100,  30,  40, 100,  60,  70])

In [122]:
#a[[r1, r2], [c1, c2]] → picks elements (r1, c1) and (r2, c2).
a[[0,2],[2,3]]

array([ 2, 15])

In [120]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [129]:
indices = (
    [0, 1, 2, 3, 4],
    [4, 3, 2, 1, 0],
)
a[indices]

array([ 4,  9, 14, 19, 24])

In [121]:
a[[0],[2]]

array([2])

In [123]:
a[[0,2,1],[2,3,5]]

array([ 2, 15, 11])

In [137]:
a[[0],[2]]
a[[0, 2],[2,3]]
a[[0,2, 1],[2,3,5]]

array([ 2, 15, 11])

Check the difference 
a[[3,5], [0,2,5]] # pair indexing
a[np.ix_([3,5], [0, 2,5])] # row 3, 5 and columns 0, 2, 5

In [138]:
#  check the difference from before
a[3:, [0,2,5]]

array([[18, 20, 23],
       [24, 26, 29],
       [30, 32, 35]])

### Indexing by Booleans

In [6]:
a = np.array([1, -4, 5, 0, -6, 7])
print(a<0)
a[a<0] = -999
a

[False  True False False  True False]


array([   1, -999,    5,    0, -999,    7])

In [118]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [119]:
mask = np.array([1,0,1,0,0,1], dtype=bool)
print(mask)
a[mask, 2]

[ True False  True False False  True]


array([ 2, 14, 32])

In [9]:
# Exercise 2 
# extract the  numbers divisible by 3 using a boolean mask 
print(a)
print(a%3)
a[a%3 == 0]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [128]:
dwind_dtype = [
    ('year', int),
    ('month', int),
    ('day', int),
    ('wind', float, (12,)),
]
data = np.loadtxt('data/wind_simple.data', dtype=wind_dtype)
wind = data['wind']
high_wind = wind[wind > 20]
high_wind

array([20.71, 20.79, 20.58, ..., 20.33, 27.29, 22.08], shape=(4647,))

## Computations with arrays
Four rules
1. Operations between multiple array objects are first checked for proper shape match.
2. Mathematical operators (+-*/ log,exp ..) apply element by emement on the values.
3. Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.
4. Missing values propagate unless explicitly ignored (nanmean, namsum, ...).


In [141]:
a = np.arange(25).reshape(5,5)
print(a)
b = a[3,:]
b[:] = 100
print(a)
print(b)

b = a.copy()
b[:] = 100
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [100 100 100 100 100]
 [ 20  21  22  23  24]]
[100 100 100 100 100]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [100 100 100 100 100]
 [ 20  21  22  23  24]]
[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


### operations 

In [142]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
a+b
a*b
a/b
a*10

array([10, 20, 30, 40])

In [143]:
# universal functions 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [147]:
a[:,0]+a[:,1]

array([ 3,  5, 13])

### Sum/Subtract methods
![Visualizing N-D arrays](img/NDarray.PNG)

In [144]:
a.sum()
# or 
np.sum(a)

10

sum along rows
a.sum(axis=0)

or 
np.sum(a, axis=0)

In [10]:
a = np.array([ [1,2,3], [2,3,4], [6,7,9] ])
a

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 9]])

In [11]:
a.sum(axis=0)

array([ 9, 12, 16])

In [12]:
a.sum(axis=1)

array([ 6,  9, 22])

In [148]:
# sum all the last axis
a.sum(axis = -1)

# or
np.sum(a, axis=-1)

array([ 6,  9, 22])

In [2]:
a = np.arange(9, dtype=np.uint8).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=uint8)

In [3]:
b = np.full((3,3), 4, np.uint8)
b

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]], dtype=uint8)

In [4]:
np.subtract(b,a)

array([[  4,   3,   2],
       [  1,   0, 255],
       [254, 253, 252]], dtype=uint8)

In [5]:
b-a

array([[  4,   3,   2],
       [  1,   0, 255],
       [254, 253, 252]], dtype=uint8)

In [152]:
a = np.arange(9, dtype=np.int32).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [153]:
b = np.full((3,3), 4, np.int32)
b

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [154]:
np.subtract(b,a)

array([[ 4,  3,  2],
       [ 1,  0, -1],
       [-2, -3, -4]])

In [ ]:
b-a

### Min/Max 

In [175]:
# min
a = np.array([[11,2,4], [5,6,7] ])
a

array([[11,  2,  4],
       [ 5,  6,  7]])

In [176]:
np.where(a>6)

(array([0, 1], dtype=int64), array([0, 2], dtype=int64))

In [179]:
np.min(a)
a.min()
a.min(axis = 1)

array([2, 5])

In [158]:
np.max(a, axis = 0)

array([11,  6,  7])

### ARGMin/Max
Many tasks are interested in the location of the min/max, not the value.

In [180]:
print(a)
a.argmax()

[[11  2  4]
 [ 5  6  7]]


0

In [160]:
a.argmin()

1

In [161]:
a.argmin(axis =0)

array([1, 0, 0], dtype=int64)

arg methods return the location in a 1D, flattened version of the original array. 
Numpp includes a function to un-flattern 1D locations 

In [162]:
np.unravel_index(a.argmax(), a.shape)

(0, 0)

In [163]:
np.unravel_index(a.argmin(), a.shape)

(0, 1)

### Where 
Numpy's where function has to distinct uses. One is to provide the coordinates from masks.

In [13]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 9]])

In [21]:
a%2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [ True, False, False]])

In [23]:
np.where(a%2 == 0)

(array([0, 1, 1, 2], dtype=int64), array([1, 0, 2, 0], dtype=int64))

In [164]:
a = np.array([1,2, 4,5,6,7])
a

array([1, 2, 4, 5, 6, 7])

In [165]:
mask = (a% 2 == 0)
mask

array([False,  True,  True, False,  True, False])

In [166]:
np.where(a% 2 == 0) 


(array([1, 2, 4], dtype=int64),)

### Where 
Where can also be used to construct a new array by chossing values from other arrays of the same shape. 

In [188]:
print(a)
np.where((a%2 == 0), 100, -99) 

[[11  2  4]
 [ 5  6  7]]


array([[-99, 100, 100],
       [-99, 100, -99]])

In [8]:
x = np.array([[[-0.26,  0.49,  0.18],
...                [ 0.43,  0.3 ,  0.29]],
...               [[-0.44,  0.3 ,  0.28],
...                [ 0.27, -0.09, -0.13]]])
print(x.shape)
bool_ind = x > 0
x[bool_ind]

(2, 2, 3)


array([0.49, 0.18, 0.43, 0.3 , 0.29, 0.3 , 0.28, 0.27])

In [189]:
a = np.arange(9).reshape((3, 3))
print(a)
print(np.where(a < 5, -1, 100))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ -1  -1  -1]
 [ -1  -1 100]
 [100 100 100]]


### Statistics array methods 


In [169]:
a = np.array([ [1, 3,4], [2,5,8] ])
a

array([[1, 3, 4],
       [2, 5, 8]])

In [170]:
#(axis=0) # on all rows
a.mean(axis=0)

array([1.5, 4. , 6. ])

In [171]:
#(axis=1) # on all columns
a.std(axis=1)

array([1.24721913, 2.44948974])

In [172]:
a.var(axis=0)

array([0.25, 1.  , 4.  ])

In [173]:
a = np.arange(-15, 15).reshape(5,6)**2
a
        

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

1. compute the maximum of each row
2. the mean of each column
3. The position of the overall minimum

In [67]:
wind_dtype = [
    ('year', int),
    ('month', int),
    ('day', int),
    ('wind', float, (12,)),
]
data = np.loadtxt('data/wind_simple.data', dtype=wind_dtype)

# axis 0 represents the days
print(data['wind'].mean(axis=0))
# axis 1 represents the locations
print(data['wind'].mean(axis=1))



[12.36371463 10.64644813 11.66010344  6.30627472 10.45688013  7.09225434
  9.7968345   8.49442044  8.49581838  8.70726803 13.121007   15.59946152]
[13.09666667 11.79833333 11.34166667 ... 14.89       15.3675
 15.4025    ]


## Application of numpy for image analysis 