In [11]:
import numpy as np

In [8]:
a = np.arange(6, dtype=np.float32).reshape(2, 3)

# Same shape & dtype as a → zeros
z1 = np.zeros_like(a)                 # shape (2,3), dtype float32
print(z1)


[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
row = np.arange(4)[None, :]           # shape (1, 4)
print(row)
col = np.arange(3)[:, None]           # shape (3, 1)
print(col)
row + col                  


[[0 1 2 3]]
[[0]
 [1]
 [2]]


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [5]:
# 2D + 1D along last axis
A = np.ones((5, 3))                   # (5, 3)
print(A)
b = np.array([10, 20, 30])            # (3,)
print(b)
A + b                                 # result (5, 3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[10 20 30]


array([[11., 21., 31.],
       [11., 21., 31.],
       [11., 21., 31.],
       [11., 21., 31.],
       [11., 21., 31.]])

In [6]:
# Mismatched unless a size is 1:
X = np.ones((2, 3))
print(X)
Y = np.ones((4, 1))
print(Y)
# X + Y  → error (2 ≠ 4 and neither is 1 on the first axis)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]]


In [26]:
SEED = 123
np.random.seed(SEED)
Y, X = np.mgrid[0:8, 0:12]
#noise = np.random.normal(0, 0.05, size=(80,120))
D = 0.3*np.sin(X/15) + 0.25*np.cos(Y/21) 
print(D)

CLS = np.zeros_like(D, dtype=int)
print(CLS)
CLS = np.where(D >= 0.0, 1, CLS)
print(CLS)
CLS = np.where(D >= 0.3, 2, CLS)
print(CLS)
CLS = np.where(D >= 0.4, 3, CLS)
print(CLS)
D.shape, CLS.shape, np.unique(CLS)


[[0.25       0.26998519 0.28988159 0.3096008  0.32905522 0.34815841
  0.3668255  0.38497356 0.40252197 0.41939274 0.43551094 0.45080495]
 [0.24971661 0.2697018  0.28959819 0.30931741 0.32877182 0.34787502
  0.36654211 0.38469017 0.40223857 0.41910935 0.43522755 0.45052156]
 [0.24886707 0.26885226 0.28874866 0.30846787 0.32792229 0.34702548
  0.36569257 0.38384063 0.40138904 0.41825981 0.43437801 0.44967202]
 [0.24745332 0.2674385  0.2873349  0.30705411 0.32650853 0.34561172
  0.36427882 0.38242688 0.39997528 0.41684606 0.43296426 0.44825827]
 [0.24547855 0.26546374 0.28536013 0.30507935 0.32453377 0.34363696
  0.36230405 0.38045211 0.39800051 0.41487129 0.43098949 0.4462835 ]
 [0.24294724 0.26293243 0.28282883 0.30254804 0.32200246 0.34110565
  0.35977275 0.37792081 0.39546921 0.41233999 0.42845819 0.4437522 ]
 [0.23986515 0.25985033 0.27974673 0.29946594 0.31892036 0.33802355
  0.35669065 0.37483871 0.39238711 0.40925789 0.42537609 0.4406701 ]
 [0.23623924 0.25622443 0.27612082 0.2958

((8, 12), (8, 12), array([1, 2, 3]))

In [20]:
x = np.array([3, 1, 2, 3, 2, 2])
a = np.unique(x)
print(a)

[1 2 3]


In [13]:
a = np.array([3, -1, 5, -2])

# Replace negatives with 0
b = np.where(a < 0, 0, a)              # → [3, 0, 5, 0]
print(b)

[3 0 5 0]


In [14]:
# Pick elementwise from two arrays
b = np.array([10, 20, 30, 40])
np.where(a % 2 == 0, a, b)         # even → from a, odd → from b

# Multiple conditions (remember parentheses)
np.where((a < 0) | (a > 4), 99, a) # <0 or >4 → 99, else keep a

array([ 3, 99, 99, 99])