## HWK -  Numpy 

In [2]:
import numpy as np


## Problem 1 — Array creation & spacing (10 pts)

1. Create an array `a` using `np.arange` that starts at `-2.5`, ends **before** `3.0`, with a step of `0.5`.
2. Create an array `b` using `np.linspace` from `-2.5` to `3.0` (inclusive) with **12** evenly spaced values.
3. In **one sentence**, explain why `a` and `b` have different lengths.


In [4]:

a = np.arange(-2.5, 3.0, 0.5)
b = np.linspace(-2.5, 3.0, num=12, endpoint=True)
explain_a_b = """
`np.arange` is step-based and excludes the stop value (3.0), while `np.linspace`
returns a specified count and, with `endpoint=True`, includes both endpoints — hence different lengths.
"""
a, b, explain_a_b


(array([-2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5]),
 array([-2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,
         3. ]),
 '\n`np.arange` is step-based and excludes the stop value (3.0), while `np.linspace`\nreturns a specified count and, with `endpoint=True`, includes both endpoints — hence different lengths.\n')

## Problem #2

In [6]:
a = np.arange(-15, 15).reshape(5,6)**2
a
        

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

1. compute the maximum of each row
2. the mean of each column
3. The position of the overall minimum

In [14]:
# 1 compute the maximum of each row
a.max(axis=1)
# 2. the mean of each column
a.mean(axis=0)
# 3.The position of the overall minimum
np.unravel_index(a.argmin(), a.shape)

0

## Problem #3 
NYC monthly temperature data format: 
Average Monthly & Annual Temperatures at Central Park,,,,,,,,,,,,,
YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL

In [3]:
Temp = np.loadtxt('http://www.geography.hunter.cuny.edu/~wenge/EDS2023F/data/NYCMet/CPannualT.csv',skiprows=2,delimiter=',')
Temp

array([[2000. ,   31.3,   37.3,   47.2,   51. ,   63.5,   71.3,   72.3,
          72.7,   66. ,   57. ,   45.3,   31.1,   53.9],
       [2001. ,   33.6,   35.9,   39.6,   54.2,   63.8,   72.9,   73.2,
          78.7,   67.7,   58.5,   52.7,   44.1,   56.3],
       [2002. ,   39.9,   40.6,   44.1,   56.1,   60.7,   71.4,   78.8,
          77.7,   70.2,   55.2,   46. ,   36. ,   56.4],
       [2003. ,   27.5,   30.1,   43.1,   49.8,   58.7,   68.3,   75.8,
          76.7,   67.9,   55.1,   50. ,   37.6,   53.4],
       [2004. ,   24.7,   35. ,   43.5,   53.6,   65.2,   71.2,   74.5,
          74.2,   69.3,   56. ,   48.2,   38.4,   54.5],
       [2005. ,   31.3,   36.5,   39.4,   55.1,   58.9,   74. ,   77.5,
          79.7,   73.3,   57.9,   49.6,   35.3,   55.8],
       [2006. ,   40.9,   35.7,   43.1,   55.7,   63.1,   71. ,   77.9,
          75.8,   66.6,   56.2,   51.9,   43.6,   56.8],
       [2007. ,   37.5,   28.2,   42.2,   50.3,   65.2,   71.4,   75. ,
          74. ,   70.3,  

1. Find out the mean, max, min standard deviation of monthly temperature for all 20 years. 
2. Find out mean and standard deviation of monthly temperature for each month.
3. find the years and months when monthly temperature greater > 80 degree F 
4. find the years and months when monthly temperature greater < 32 degree F
5. Classify July temperature into 3 classes:
Class 0: T < 75F
Class 1: 75F ≤ D < 80F
Class 2: T ≥ 80F

In [17]:
Temp_mon = Temp[:,1:-1]

# 1. Find out the mean, max, min standard deviation of monthly temperature for all 20 years.
Temp_mon.mean()
Temp_mon.max()
Temp_mon.std()

# 2. Find out mean and standard deviation of monthly temperature for each month.
Temp_mon.mean(axis=0)
Temp_mon.std(axis=0)   

# 3. Find the years and months when monthly temperature greater > 80 degree F
np.where(Temp_mon > 80)

# 4. Find the years and months when monthly temperature greater < 32 degree F
np.where(Temp_mon > 32)


NameError: name 'Temp' is not defined

In [54]:
Temp_mon = Temp[:,1:-1]
np.where(Temp_mon > 80)

(array([10, 11], dtype=int64), array([6, 6], dtype=int64))

In [46]:

Temp_mon.mean(axis=0)
Temp_mon.std(axis=0)   

array([4.36919229, 4.40568587, 3.64876272, 2.33319727, 2.48451896,
       1.66236179, 2.52301874, 1.98182215, 2.10070715, 2.42263514,
       3.13391223, 4.28859163])

In [4]:
$5 
import numpy as np
Ttype =[
    ('YEAR', int),
    ('JAN', float),
    ('FEB', float),
    ('MAR', float),
    ('APL', float),
    ('MAY', float),
    ('JUN', float),  
    ('JUL', float),
    ('AUG', float),
    ('SEP', float), 
    ('OCT', float),
    ('NOV', float),
    ('DEC', float),
    ('ANNUAL', float)
]
T = np.loadtxt('data/CPAnnualT.csv', skiprows = 2, delimiter =',', dtype=Ttype)
print(T['YEAR'])
print(T['JUL'])

[2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019 2020]
[72.3 73.2 78.8 75.8 74.5 77.5 77.9 75.  78.4 72.7 81.3 80.2 78.8 79.8
 76.1 78.8 78.7 76.8 77.6 79.6 80. ]


In [16]:
Tjul = T['JUL']
print(type(Tjul))
CLS = np.zeros_like(Tjul, dtype=int)

CLS = np.where(Tjul < 75, 1, CLS)
print(CLS)
CLS = np.where( (Tjul < 80) & (Tjul >= 75), 2, CLS)
print(CLS)
CLS = np.where(Tjul >= 80, 3, CLS)
print(CLS)

<class 'numpy.ndarray'>
[1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[1 1 2 2 1 2 2 2 2 1 0 0 2 2 2 2 2 2 2 2 0]
[1 1 2 2 1 2 2 2 2 1 3 3 2 2 2 2 2 2 2 2 3]


In [19]:
T = np.genfromtxt('data/CPAnnualT.csv', skip_header =1, delimiter =',', names = True)
T.dtype.names

('YEAR',
 'JAN',
 'FEB',
 'MAR',
 'APR',
 'MAY',
 'JUN',
 'JUL',
 'AUG',
 'SEP',
 'OCT',
 'NOV',
 'DEC',
 'ANNUAL')

In [ ]:
print